### ISSUE TITLE
API should be identified via User-Agent

### ISSUE THREAD

**Issue by gilgamec** [mstksg/advent-of-code-api#2]
It's been announced on Reddit (https://www.reddit.com/r/adventofcode/comments/z9dhtd) that automated requests with anonymous User-Agents will likely be blocked from accessing the API. It appears that in order to keep this package working, a more specific User-Agent should be sent. (Perhaps this is already done by this package; I'm not really clear how the User-Agent is selected for servant-client.)

**Comment by gilgamec** [comment]
This was never a problem during AoC 2022, at least. Maybe it's a non-issue?

**Comment by mstksg** [comment]
thanks for bringing this up, this was added in 0.2.9! :)
